### ISSUE TITLE
csdl native source code

### ISSUE THREAD

**Issue by leandroconsiglio** [aspriddell/csdl#1]
Hi!, I found the project very interesting. Reviewing the code I could not find the source code of csdl.native. Could you upload the csdl.native code? I'm interested in seeing how you managed to compile and generate the libtorrent library and then consume it from csdl.
Thank you!

**Comment by aspriddell** [comment]
All the csdl.Native contents are built from the [`native`](https://github.com/aspriddell/csdl/tree/master/native) folder:

- [`native/include`](https://github.com/aspriddell/csdl/tree/master/native/include) contains the header files and the C-Style interface that is used to talk with .NET
- [`native/src`](https://github.com/aspriddell/csdl/tree/master/native/src) has the implementations of the methods in the headers
- [`native/nuget`](https://github.com/aspriddell/csdl/tree/master/native/nuget) and [`native/build`](https://github.com/aspriddell/csdl/tree/master/native/build) are used for building/packaging

The project uses vcpkg as a package manager to install libtorrent, and is then made available to the c++ project via CMakeLists.txt, though if you were to clone/experiment with the native-side you'd need to setup your environment to use it (either using the submodule or cloning it somewhere centrally and configuring CMake to use it)
